#!/bin/bash
#SBATCH --partition=unkillable 
#SBATCH --cpus-per-task=4
#SBATCH --gres=gpu:a100:1
#SBATCH --time=2:00:00
#SBATCH --mem=30G
#SBATCH --output=job_output_%j.txt
#SBATCH --error=job_error_%j.txt

source ~/miniconda3/etc/profile.d/conda.sh
conda activate myenv

export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True

python whisper_test.py
